
ALTER TABLE public.clients
  ADD COLUMN IF NOT EXISTS person_type TEXT DEFAULT 'pj',
  ADD COLUMN IF NOT EXISTS cpf TEXT,
  ADD COLUMN IF NOT EXISTS rg TEXT,
  ADD COLUMN IF NOT EXISTS razao_social TEXT,
  ADD COLUMN IF NOT EXISTS inscricao_estadual TEXT;
